name: "luv-shared"

on:
  push:
    branches:
      - '*'

jobs:
    build-linux:
      runs-on: ubuntu-latest
      steps:
        - name: Install Dependencies
          run: |
            sudo apt update
            sudo apt install -y libxrandr-dev \
              libgles2-mesa-dev mesa-common-dev libgl1-mesa-dev mesa-vulkan-drivers \
              libfreetype6-dev xorg-dev libxi-dev libx11-dev libasound2-dev \
              nvidia-cg-dev glslang-dev spirv-tools spirv-headers
        - uses: actions/checkout@v4
          with:
            fetch-depth: 2
        - name: Build luv lib for Linux
          run: |
            ./build-luv.sh linux
        
        - name: Archive results
          uses: actions/upload-artifact@v4
          with:
            name: Linux luv
            path: |
              ./bin/libluv.so 

    build-windows:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v4
          with: 
            submodules: true
        - uses: ilammy/msvc-dev-cmd@v1.4.1
        - name: Build luv lib for Win64
          run: ./msvcbuild.bat
          shell: bash
           
        - name: Archive results
          uses: actions/upload-artifact@v4
          with:
            name: Windows luv
            path: |
              ./luv/build/Release/luv.dll
              
    build-macos:
      runs-on: macos-13
      steps:
        - uses: actions/checkout@v4
        - name: Build luv lib for macos
          run: ./build-luv.sh macosx
              
        - name: Archive results
          uses: actions/upload-artifact@v4
          with:
            name: macOS luv
            path: |
              ./bin/libluv_macos.so 
    build-macos-arm64:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v4
        - name: Build luv lib for macos arm64
          run: ./build-luv.sh macos_arm64
              
        - name: Archive results
          uses: actions/upload-artifact@v4
          with:
            name: macOS arm64 luv
            path: |
              ./bin/libluv_macos_arm64.so 
    build-ios64:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v4
        - name: Build luv lib for iosarm64
          run: ./build-luv.sh ios64
              
        - name: Archive results
          uses: actions/upload-artifact@v4
          with:
            name: ios64 luv
            path: |
              ./bin/libluv_ios64.so 
    
